method: random
metric:
  name: FID
  goal: minimize
parameters:
  train_ratio: 
    value: 0.9
  batch_size:
    values: 64
  lr:
    value: 0.003
  epochs:
    value: 250
  n_feat_dim: 
    value: 4
  embed_dim: 
    value: 256
  hidden_dim: 
    values: [48,64,96]
  num_encoder_blocks: 
    values: [4,8,16]
  num_attn_heads: 
    values: [4,8,16]
  dropout_gen:
    value: 0.2
  SDE:
    values: ["VP","subVP","VE"]
  sigma_max: 
    values: [0.5,1.0,2.0,5.0,10.0]
  sigma_min: 
    values: [0.0001,0.005,0.001,0.003,0.005]
  sampler_steps:
    values: [50,100,500,1000]
  n_showers_2_gen: 
    value: 2000
  correction_steps:
    values: [10,25,50]
