method: random
metric:
  name: FID
  goal: minimize
parameters:
  train_ratio: 
    value: 0.9
  batch_size:
    value: 128
  lr:
    value: 0.003
  epochs:
    value: 300
  n_feat_dim: 
    value: 4
  embed_dim: 
    values: [16,32,48,64,96,128,160,256]
  hidden_dim: 
    values: [16,32,48,64,96,128,160,256]
  num_encoder_blocks: 
    values: [4,8]
  num_attn_heads: 
    values: [4,8,16]
  dropout_gen:
    value: 0.2
  SDE:
    values: ["VP","VE","subVP"]
  sigma_max: 
    value: 1.0
  sigma_min: 
    value: 0.003
  sampler_steps:
    values: [50,100,500,1000]
  n_showers_2_gen: 
    value: 2000
  correction_steps:
    values: [50,100,500,1000]