method: random
metric:
  name: FID
  goal: minimize
parameters:
  train_ratio: 
    value: 0.9
  batch_size:
    value: 64
  lr:
    value: 0.003
  epochs:
    value: 100
  n_feat_dim: 
    value: 4
  embed_dim: 
    value: 256
  hidden_dim: 
    value: 128
  num_encoder_blocks: 
    value: 16
  num_attn_heads: 
    value: 16
  dropout_gen:
    value: 0.2
  SDE:
    values: ["VP","VE","subVP"]
  sigma_max: 
    values: [0.5,1.0,2.0,5.0,10.0]
  sigma_min: 
    values: [0.0001,0.001,0.003,0.01]
  sampler_steps:
    value: 100
  correction_steps:
    value: 25
  n_showers_2_gen: 
    value: 200
