method: grid
metric:
  name: FID
  goal: minimize
parameters:
  train_ratio: 
    value: 0.9
  batch_size:
    value: 128
  lr:
    value: 0.003
  epochs:
    value: 5
  n_feat_dim: 
    value: 4
  embed_dim: 
    values: [4,8]
  hidden_dim: 
    values: [4,8]
  num_encoder_blocks: 
    values: [4,8]
  num_attn_heads: 
    values: [4,8]
  dropout_gen:
    value: 0.2
  SDE:
    values: ["VP","VE"]
  sigma_max: 
    value: 1.0
  sigma_min: 
    value: 0.003
  sampler_steps:
    value: 100
  n_showers_2_gen: 
    value: 200